In [149]:
import pandas as pd

In [150]:
llm_error = pd.read_csv(
    "../llmerr.tsv", sep="\t", header=None, names=["model", "input", "result"]
)

In [151]:
llm_error

,model,input,result
0,anthropic/claude_opus_4.7,100--234 nanosecs,"[SimulationTime(value=100.0, unit='ns'), Simu..."
1,anthropic/claude_opus_4.7,100--234 nanosecs,"[SimulationTime(value=100.0, unit='ns'), Simu..."
2,anthropic/claude_opus_4.7,100--234 nanosecs,"[SimulationTime(value=100.0, unit='ns'), Simu..."
3,anthropic/claude_opus_4.7,100--234 nanosecs,"[SimulationTime(value=100.0, unit='ns'), Simu..."
4,anthropic/claude_opus_4.7,100--234 nanosecs,"[SimulationTime(value=100.0, unit='ns'), Simu..."
...,...,...,...
631,qwen/qwen3.6_27b,nanosecond,failed after 3 attempts
632,qwen/qwen3.6_27b,one hundred nanosecond,failed after 3 attempts
633,qwen/qwen3.6_27b,one hundred nanosecond,failed after 3 attempts
634,qwen/qwen3.6_27b,one hundred nanosecond,failed after 3 attempts
635,qwen/qwen3.6_27b,us,failed after 3 attempts

In [152]:
llm_error.groupby(["model", "input", "result"]).size()

model                       input                   result
anthropic/claude_opus_4.7   100--234 nanosecs        [SimulationTime(value=100.0, unit='ns'), SimulationTime(value=234.0, unit='ns')]    10
                            298k                     [SimulationTime(value=298000.0, unit=None)]                                         10
                            350million               [SimulationTime(value=350000000.0, unit=None)]                                      10
deepseek/deepseek_v4_pro    0.5 μs                  failed after 3 attempts                                                               1
                            0.6                     failed after 3 attempts                                                               2
                                                                                                                                         ..
qwen/qwen3.6_27b            microsecond             failed after 3 attempts                                                               1
                            multi-microsecond        [SimulationTime(value=1.0, unit='ns')]                                               1
                            nanosecond              failed after 3 attempts                                                               2
                            one hundred nanosecond  failed after 3 attempts                                                               3
                            us                      failed after 3 attempts                                                               1
Length: 230, dtype: int64

In [153]:
llm_error

,model,input,result
0,anthropic/claude_opus_4.7,100--234 nanosecs,"[SimulationTime(value=100.0, unit='ns'), Simu..."
1,anthropic/claude_opus_4.7,100--234 nanosecs,"[SimulationTime(value=100.0, unit='ns'), Simu..."
2,anthropic/claude_opus_4.7,100--234 nanosecs,"[SimulationTime(value=100.0, unit='ns'), Simu..."
3,anthropic/claude_opus_4.7,100--234 nanosecs,"[SimulationTime(value=100.0, unit='ns'), Simu..."
4,anthropic/claude_opus_4.7,100--234 nanosecs,"[SimulationTime(value=100.0, unit='ns'), Simu..."
...,...,...,...
631,qwen/qwen3.6_27b,nanosecond,failed after 3 attempts
632,qwen/qwen3.6_27b,one hundred nanosecond,failed after 3 attempts
633,qwen/qwen3.6_27b,one hundred nanosecond,failed after 3 attempts
634,qwen/qwen3.6_27b,one hundred nanosecond,failed after 3 attempts
635,qwen/qwen3.6_27b,us,failed after 3 attempts

In [154]:
llm_error_count = pd.DataFrame(llm_error.value_counts())

In [155]:
llm_error_count = llm_error_count.reset_index()

In [156]:
llm_error_count

,model,input,result,count
0,anthropic/claude_opus_4.7,100--234 nanosecs,"[SimulationTime(value=100.0, unit='ns'), Simu...",10
1,anthropic/claude_opus_4.7,298k,"[SimulationTime(value=298000.0, unit=None)]",10
2,anthropic/claude_opus_4.7,350million,"[SimulationTime(value=350000000.0, unit=None)]",10
3,google/gemma_4_31b_it,20 C,"[SimulationTime(value=20.0, unit='s')]",10
4,google/gemma_4_31b_it,213fentosecs,"[SimulationTime(value=0.213, unit='ps')]",10
...,...,...,...,...
225,qwen/qwen3.6_27b,87 microsecond,failed after 3 attempts,1
226,qwen/qwen3.6_27b,8 microseconds,failed after 3 attempts,1
227,qwen/qwen3.6_27b,microsecond,failed after 3 attempts,1
228,qwen/qwen3.6_27b,multi-microsecond,"[SimulationTime(value=1.0, unit='ns')]",1
229,qwen/qwen3.6_27b,us,failed after 3 attempts,1

In [157]:
llm_error_count["total"] = llm_error_count.groupby("model")["count"].transform("sum")

In [158]:
llm_error_count

,model,input,result,count,total
0,anthropic/claude_opus_4.7,100--234 nanosecs,"[SimulationTime(value=100.0, unit='ns'), Simu...",10,30
1,anthropic/claude_opus_4.7,298k,"[SimulationTime(value=298000.0, unit=None)]",10,30
2,anthropic/claude_opus_4.7,350million,"[SimulationTime(value=350000000.0, unit=None)]",10,30
3,google/gemma_4_31b_it,20 C,"[SimulationTime(value=20.0, unit='s')]",10,207
4,google/gemma_4_31b_it,213fentosecs,"[SimulationTime(value=0.213, unit='ps')]",10,207
...,...,...,...,...,...
225,qwen/qwen3.6_27b,87 microsecond,failed after 3 attempts,1,117
226,qwen/qwen3.6_27b,8 microseconds,failed after 3 attempts,1,117
227,qwen/qwen3.6_27b,microsecond,failed after 3 attempts,1,117
228,qwen/qwen3.6_27b,multi-microsecond,"[SimulationTime(value=1.0, unit='ns')]",1,117
229,qwen/qwen3.6_27b,us,failed after 3 attempts,1,117

In [159]:
llm_error_count.sort_values(by=["model", "input", "result"], inplace=True)

In [160]:
llm_error_count

,model,input,result,count,total
0,anthropic/claude_opus_4.7,100--234 nanosecs,"[SimulationTime(value=100.0, unit='ns'), Simu...",10,30
1,anthropic/claude_opus_4.7,298k,"[SimulationTime(value=298000.0, unit=None)]",10,30
2,anthropic/claude_opus_4.7,350million,"[SimulationTime(value=350000000.0, unit=None)]",10,30
104,deepseek/deepseek_v4_pro,0.5 μs,failed after 3 attempts,1,50
64,deepseek/deepseek_v4_pro,0.6,failed after 3 attempts,2,50
...,...,...,...,...,...
227,qwen/qwen3.6_27b,microsecond,failed after 3 attempts,1,117
228,qwen/qwen3.6_27b,multi-microsecond,"[SimulationTime(value=1.0, unit='ns')]",1,117
103,qwen/qwen3.6_27b,nanosecond,failed after 3 attempts,2,117
63,qwen/qwen3.6_27b,one hundred nanosecond,failed after 3 attempts,3,117
229,qwen/qwen3.6_27b,us,failed after 3 attempts,1,117

In [161]:
llm_error_count = llm_error_count.loc[:, ["total", "count", "model", "input", "result"]]

In [162]:
llm_error_count = llm_error_count.sort_values(["total", "count"], ascending=False)

In [163]:
llm_error_count.to_csv("output.tsv", sep="\t", index=False)