In [2]:
%load_ext autoreload
%autoreload 2
import json

import gilda
import httpx
import pandas as pd

from mdverse_entity_norm.scripts.ground_molecule import (
    call_chebi,
    call_gilda,
    call_pubchem,
    get_type,
)

/data/zenati/mdverse_entity_norm/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
results = call_chebi("popc")
results

INFO: [2026-03-30 12:26:11] httpx - HTTP Request: GET https://www.ebi.ac.uk/chebi/backend/api/public/es_search/?term=popc&page=1&size=5 "HTTP/1.1 200 OK"
2026-03-30 12:26:11.984 | DEBUG    | mdverse_entity_norm.scripts.ground_molecule:call_chebi:123 - Status HTTP : 200 (The request succeeded for `popc`)

{'chebi_id': '73001',
 'score': 38.634285,
 'name': '1-hexadecanoyl-2-(9Z-octadecenoyl)-sn-glycero-3-phosphocholine',
 'star': 3}

In [27]:
resultsg = gilda.ground("1-palmitoyl-2-oleoyl-sn-glycero-3-phosphocholine")
resultsg[0].to_json()

{'term': {'norm_text': '1palmitoyl2oleoylsnglycero3phosphocholine',
  'text': '1-palmitoyl-2-oleoyl-sn-glycero-3-phosphocholine',
  'db': 'CHEBI',
  'id': 'CHEBI:73001',
  'entry_name': '1-hexadecanoyl-2-(9Z-octadecenoyl)-sn-glycero-3-phosphocholine',
  'status': 'synonym',
  'source': 'mesh',
  'source_db': 'MESH',
  'source_id': 'C028694'},
 'url': 'https://bioregistry.io/chebi:73001',
 'score': 0.5555555555555556,
 'match': {'query': '1-palmitoyl-2-oleoyl-sn-glycero-3-phosphocholine',
  'ref': '1-palmitoyl-2-oleoyl-sn-glycero-3-phosphocholine',
  'exact': True,
  'space_mismatch': False,
  'dash_mismatches': [],
  'cap_combos': []}}

In [10]:
data = results.items
data

In [ ]:
results.content

b'{"audit_author":[{"name":"Wrapp, D.","pdbx_ordinal":1},{"name":"Wang, N.","pdbx_ordinal":2},{"name":"Corbett, K.S.","pdbx_ordinal":3},{"name":"Goldsmith, J.A.","pdbx_ordinal":4},{"name":"Hsieh, C.","pdbx_ordinal":5},{"name":"Abiona, O.","pdbx_ordinal":6},{"name":"Graham, B.S.","pdbx_ordinal":7},{"name":"McLellan, J.S.","pdbx_ordinal":8}],"citation":[{"country":"US","id":"primary","journal_abbrev":"Science","journal_id_astm":"SCIEAS","journal_id_csd":"0038","journal_id_issn":"1095-9203","journal_volume":"367","page_first":"1260","page_last":"1263","pdbx_database_id_doi":"10.1126/science.abb2507","pdbx_database_id_pub_med":32075877,"rcsb_authors":["Wrapp, D.","Wang, N.","Corbett, K.S.","Goldsmith, J.A.","Hsieh, C.L.","Abiona, O.","Graham, B.S.","McLellan, J.S."],"rcsb_is_primary":"Y","rcsb_journal_abbrev":"Science","title":"Cryo-EM structure of the 2019-nCoV spike in the prefusion conformation.","year":2020}],"database2":[{"database_code":"6VSB","database_id":"PDB","pdbx_doi":"10.2210/pdb6vsb/pdb","pdbx_database_accession":"pdb_00006vsb"},{"database_code":"D_1000246985","database_id":"WWPDB"},{"database_code":"EMD-21375","database_id":"EMDB"}],"em3d_fitting":[{"id":"1"}],"em3d_reconstruction":[{"id":"1","image_processing_id":"1","num_particles":120001,"resolution":3.46,"resolution_method":"FSC 0.143 CUT-OFF","symmetry_type":"POINT"}],"em_ctf_correction":[{"em_image_processing_id":"1","id":"1","type":"PHASE FLIPPING AND AMPLITUDE CORRECTION"}],"em_entity_assembly":[{"entity_id_list":["1"],"id":"1","name":"SARS-CoV-2 spike glycoprotein","parent_id":0,"source":"RECOMBINANT","type":"COMPLEX"}],"em_experiment":{"aggregation_state":"PARTICLE","entity_assembly_id":"1","id":"1","reconstruction_method":"SINGLE PARTICLE"},"em_image_recording":[{"avg_electron_dose_per_image":37.8,"film_or_detector_model":"GATAN K3 (6k x 4k)","id":"1","imaging_id":"1"}],"em_imaging":[{"accelerating_voltage":300,"electron_source":"FIELD EMISSION GUN","id":"1","illumination_mode":"FLOOD BEAM","microscope_model":"FEI TITAN KRIOS","mode":"BRIGHT FIELD","specimen_id":"1"}],"em_single_particle_entity":[{"id":1,"image_processing_id":"1","point_symmetry":"C1"}],"em_software":[{"category":"CRYSTALLOGRAPHY MERGING","fitting_id":"1","id":"1","image_processing_id":"1","imaging_id":"1"},{"category":"IMAGE ACQUISITION","id":"2","imaging_id":"1","name":"Leginon"},{"category":"MASKING","id":"3"},{"category":"CTF CORRECTION","id":"4","image_processing_id":"1","name":"Warp"},{"category":"LAYERLINE INDEXING","id":"5"},{"category":"DIFFRACTION INDEXING","id":"6"},{"category":"MODEL FITTING","id":"7"},{"category":"MODEL REFINEMENT","id":"8"},{"category":"OTHER","id":"9"},{"category":"INITIAL EULER ASSIGNMENT","id":"10","image_processing_id":"1","name":"cryoSPARC"},{"category":"FINAL EULER ASSIGNMENT","id":"11","image_processing_id":"1","name":"cryoSPARC"},{"category":"CLASSIFICATION","id":"12","image_processing_id":"1"},{"category":"RECONSTRUCTION","id":"13","image_processing_id":"1","name":"cryoSPARC"}],"em_specimen":[{"concentration":0.35,"embedding_applied":"NO","experiment_id":"1","id":"1","shadowing_applied":"NO","staining_applied":"NO","vitrification_applied":"YES"}],"em_vitrification":[{"chamber_temperature":277.15,"cryogen_name":"ETHANE","humidity":100.0,"id":"1","instrument":"FEI VITROBOT MARK IV","specimen_id":"1"}],"entry":{"id":"6VSB"},"exptl":[{"method":"ELECTRON MICROSCOPY"}],"pdbx_audit_revision_category":[{"category":"citation","data_content_type":"Structure model","ordinal":1,"revision_ordinal":2},{"category":"citation_author","data_content_type":"Structure model","ordinal":2,"revision_ordinal":2},{"category":"citation","data_content_type":"Structure model","ordinal":3,"revision_ordinal":3},{"category":"em_entity_assembly","data_content_type":"Structure model","ordinal":4,"revision_ordinal":4},{"category":"em_entity_assembly_naturalsource","data_content_type":"Structure model","ordinal":5,"revision_ordinal":4},{"category":"entity","data_content_type":"Structure model","ordinal":6,"revision_ordinal":4},{"category":"entity_src_gen","data_content_type":"Structure model","ordinal":7,"revision_ordinal":4},{"category":"entity_name_com","data_content_type":"Structure model","ordinal":8,"revision_ordinal":5},{"category":"entity_src_gen","data_content_type":"Structure model","ordinal":9,"revision_ordinal":5},{"category":"struct_ref","data_content_type":"Structure model","ordinal":10,"revision_ordinal":5},{"category":"struct_ref_seq","data_content_type":"Structure model","ordinal":11,"revision_ordinal":5},{"category":"struct_ref_seq_dif","data_content_type":"Structure model","ordinal":12,"revision_ordinal":5},{"category":"atom_site","data_content_type":"Structure model","ordinal":13,"revision_ordinal":6},{"category":"chem_comp","data_content_type":"Structure model","ordinal":14,"revision_ordinal":6},{"category":"entity","data_content_type":"Structure model","ordinal":15,"revision_ordinal":6},{"category":"pdbx_branch_scheme","data_content_type":"Structure model","ordinal":16,"revision_ordinal":6},{"category":"pdbx_chem_comp_identifier","data_content_type":"Structure model","ordinal":17,"revision_ordinal":6},{"category":"pdbx_entity_branch","data_content_type":"Structure model","ordinal":18,"revision_ordinal":6},{"category":"pdbx_entity_branch_descriptor","data_content_type":"Structure model","ordinal":19,"revision_ordinal":6},{"category":"pdbx_entity_branch_link","data_content_type":"Structure model","ordinal":20,"revision_ordinal":6},{"category":"pdbx_entity_branch_list","data_content_type":"Structure model","ordinal":21,"revision_ordinal":6},{"category":"pdbx_entity_nonpoly","data_content_type":"Structure model","ordinal":22,"revision_ordinal":6},{"category":"pdbx_nonpoly_scheme","data_content_type":"Structure model","ordinal":23,"revision_ordinal":6},{"category":"pdbx_struct_assembly_gen","data_content_type":"Structure model","ordinal":24,"revision_ordinal":6},{"category":"pdbx_validate_close_contact","data_content_type":"Structure model","ordinal":25,"revision_ordinal":6},{"category":"struct_asym","data_content_type":"Structure model","ordinal":26,"revision_ordinal":6},{"category":"struct_conn","data_content_type":"Structure model","ordinal":27,"revision_ordinal":6},{"category":"struct_site","data_content_type":"Structure model","ordinal":28,"revision_ordinal":6},{"category":"struct_site_gen","data_content_type":"Structure model","ordinal":29,"revision_ordinal":6},{"category":"entity","data_content_type":"Structure model","ordinal":30,"revision_ordinal":7},{"category":"entity_name_com","data_content_type":"Structure model","ordinal":31,"revision_ordinal":7},{"category":"chem_comp_atom","data_content_type":"Structure model","ordinal":32,"revision_ordinal":8},{"category":"chem_comp_bond","data_content_type":"Structure model","ordinal":33,"revision_ordinal":8},{"category":"database_2","data_content_type":"Structure model","ordinal":34,"revision_ordinal":8},{"category":"em_admin","data_content_type":"Structure model","ordinal":35,"revision_ordinal":8},{"category":"pdbx_entry_details","data_content_type":"Structure model","ordinal":36,"revision_ordinal":8},{"category":"pdbx_modification_feature","data_content_type":"Structure model","ordinal":37,"revision_ordinal":8}],"pdbx_audit_revision_details":[{"data_content_type":"Structure model","ordinal":1,"provider":"repository","revision_ordinal":1,"type":"Initial release"},{"data_content_type":"Structure model","description":"Carbohydrate remediation","ordinal":2,"provider":"repository","revision_ordinal":6,"type":"Remediation"}],"pdbx_audit_revision_group":[{"data_content_type":"Structure model","group":"Database references","ordinal":1,"revision_ordinal":2},{"data_content_type":"Structure model","group":"Database references","ordinal":2,"revision_ordinal":3},{"data_content_type":"Structure model","group":"Source and taxonomy","ordinal":3,"revision_ordinal":4},{"data_content_type":"Structure model","group":"Structure summary","ordinal":4,"revision_ordinal":4},{"data_content_type":"Structure model","group":"Database references","ordinal":5,"revision_ordinal":5},{"data_content_type":"Structure model","group":"Source and taxonomy","ordinal":6,"revision_ordinal":5},{"data_content_type":"Structure model","group":"Structure summary","ordinal":7,"revision_ordinal":5},{"data_content_type":"Structure model","group":"Advisory","ordinal":8,"revision_ordinal":6},{"data_content_type":"Structure model","group":"Atomic model","ordinal":9,"revision_ordinal":6},{"data_content_type":"Structure model","group":"Data collection","ordinal":10,"revision_ordinal":6},{"data_content_type":"Structure model","group":"Derived calculations","ordinal":11,"revision_ordinal":6},{"data_content_type":"Structure model","group":"Structure summary","ordinal":12,"revision_ordinal":6},{"data_content_type":"Structure model","group":"Structure summary","ordinal":13,"revision_ordinal":7},{"data_content_type":"Structure model","group":"Data collection","ordinal":14,"revision_ordinal":8},{"data_content_type":"Structure model","group":"Database references","ordinal":15,"revision_ordinal":8},{"data_content_type":"Structure model","group":"Structure summary","ordinal":16,"revision_ordinal":8}],"pdbx_audit_revision_history":[{"data_content_type":"Structure model","major_revision":1,"minor_revision":0,"ordinal":1,"revision_date":"2020-02-26T00:00:00+0000"},{"data_content_type":"Structure model","major_revision":1,"minor_revision":1,"ordinal":2,"revision_date":"2020-03-04T00:00:00+0000"},{"data_content_type":"Structure model","major_revision":1,"minor_revision":2,"ordinal":3,"revision_date":"2020-03-25T00:00:00+0000"},{"data_content_type":"Structure model","major_revision":1,"minor_revision":3,"ordinal":4,"revision_date":"2020-04-01T00:00:00+0000"},{"data_content_type":"Structure model","major_revision":1,"minor_revision":4,"ordinal":5,"revision_date":"2020-05-06T00:00:00+0000"},{"data_content_type":"Structure model","major_revision":2,"minor_revision":0,"ordinal":6,"revision_date":"2020-07-29T00:00:00+0000"},{"data_content_type":"Structure model","major_revision":2,"minor_revision":1,"ordinal":7,"revision_date":"2021-01-27T00:00:00+0000"},{"data_content_type":"Structure model","major_revision":2,"minor_revision":2,"ordinal":8,"revision_date":"2024-10-23T00:00:00+0000"}],"pdbx_audit_revision_item":[{"data_content_type":"Structure model","item":"_citation.pdbx_database_id_PubMed","ordinal":1,"revision_ordinal":2},{"data_content_type":"Structure model","item":"_citation.title","ordinal":2,"revision_ordinal":2},{"data_content_type":"Structure model","item":"_citation_author.name","ordinal":3,"revision_ordinal":2},{"data_content_type":"Structure model","item":"_citation.journal_volume","ordinal":4,"revision_ordinal":3},{"data_content_type":"Structure model","item":"_citation.page_first","ordinal":5,"revision_ordinal":3},{"data_content_type":"Structure model","item":"_citation.page_last","ordinal":6,"revision_ordinal":3},{"data_content_type":"Structure model","item":"_em_entity_assembly.name","ordinal":7,"revision_ordinal":4},{"data_content_type":"Structure model","item":"_em_entity_assembly_naturalsource.organism","ordinal":8,"revision_ordinal":4},{"data_content_type":"Structure model","item":"_entity.pdbx_description","ordinal":9,"revision_ordinal":4},{"data_content_type":"Structure model","item":"_entity_src_gen.gene_src_common_name","ordinal":10,"revision_ordinal":4},{"data_content_type":"Structure model","item":"_entity_src_gen.pdbx_gene_src_scientific_name","ordinal":11,"revision_ordinal":4},{"data_content_type":"Structure model","item":"_entity_src_gen.gene_src_common_name","ordinal":12,"revision_ordinal":5},{"data_content_type":"Structure model","item":"_entity_src_gen.pdbx_gene_src_gene","ordinal":13,"revision_ordinal":5},{"data_content_type":"Structure model","item":"_struct_ref.db_code","ordinal":14,"revision_ordinal":5},{"data_content_type":"Structure model","item":"_struct_ref.db_name","ordinal":15,"revision_ordinal":5},{"data_content_type":"Structure model","item":"_struct_ref.pdbx_db_accession","ordinal":16,"revision_ordinal":5},{"data_content_type":"Structure model","item":"_struct_ref.pdbx_seq_one_letter_code","ordinal":17,"revision_ordinal":5},{"data_content_type":"Structure model","item":"_struct_ref_seq.db_align_end","ordinal":18,"revision_ordinal":5},{"data_content_type":"Structure model","item":"_struct_ref_seq.pdbx_auth_seq_align_end","ordinal":19,"revision_ordinal":5},{"data_content_type":"Structure model","item":"_struct_ref_seq.pdbx_db_accession","ordinal":20,"revision_ordinal":5},{"data_content_type":"Structure model","item":"_struct_ref_seq.seq_align_end","ordinal":21,"revision_ordinal":5},{"data_content_type":"Structure model","item":"_atom_site.B_iso_or_equiv","ordinal":22,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_atom_site.Cartn_x","ordinal":23,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_atom_site.Cartn_y","ordinal":24,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_atom_site.Cartn_z","ordinal":25,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_atom_site.auth_asym_id","ordinal":26,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_atom_site.auth_seq_id","ordinal":27,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_atom_site.label_asym_id","ordinal":28,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_atom_site.label_entity_id","ordinal":29,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_chem_comp.name","ordinal":30,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_pdbx_entity_nonpoly.entity_id","ordinal":31,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_pdbx_entity_nonpoly.name","ordinal":32,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_pdbx_struct_assembly_gen.asym_id_list","ordinal":33,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_pdbx_validate_close_contact.auth_asym_id_1","ordinal":34,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_pdbx_validate_close_contact.auth_asym_id_2","ordinal":35,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_pdbx_validate_close_contact.auth_seq_id_1","ordinal":36,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_pdbx_validate_close_contact.auth_seq_id_2","ordinal":37,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_struct_conn.pdbx_role","ordinal":38,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_struct_conn.ptnr1_auth_asym_id","ordinal":39,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_struct_conn.ptnr1_auth_seq_id","ordinal":40,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_struct_conn.ptnr1_label_asym_id","ordinal":41,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_struct_conn.ptnr2_auth_asym_id","ordinal":42,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_struct_conn.ptnr2_auth_seq_id","ordinal":43,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_struct_conn.ptnr2_label_asym_id","ordinal":44,"revision_ordinal":6},{"data_content_type":"Structure model","item":"_entity.pdbx_description","ordinal":45,"revision_ordinal":7},{"data_content_type":"Structure model","item":"_entity_name_com.name","ordinal":46,"revision_ordinal":7},{"data_content_type":"Structure model","item":"_database_2.pdbx_DOI","ordinal":47,"revision_ordinal":8},{"data_content_type":"Structure model","item":"_database_2.pdbx_database_accession","ordinal":48,"revision_ordinal":8},{"data_content_type":"Structure model","item":"_em_admin.last_update","ordinal":49,"revision_ordinal":8},{"data_content_type":"Structure model","item":"_pdbx_entry_details.has_protein_modification","ordinal":50,"revision_ordinal":8}],"pdbx_audit_support":[{"country":"United States","funding_organization":"National Institutes of Health/National Institute Of Allergy and Infectious Diseases (NIH/NIAID)","grant_number":"R01-AI127521","ordinal":1}],"pdbx_database_related":[{"content_type":"associated EM volume","db_id":"EMD-21375","db_name":"EMDB","details":"Prefusion 2019-nCoV spike glycoprotein with a single receptor-binding domain up"},{"content_type":"other EM volume","db_id":"EMD-21374","db_name":"EMDB"}],"pdbx_database_status":{"deposit_site":"RCSB","pdb_format_compatible":"Y","process_site":"RCSB","recvd_initial_deposition_date":"2020-02-10T00:00:00+0000","status_code":"REL","sgentry":"N"},"pdbx_vrpt_summary":{"attempted_validation_steps":"visualanalysis,molprobity,validation-pack,mogul,buster-report,percentiles,writexml,writecif,writepdf","ligands_for_buster_report":"N","report_creation_date":"2024-10-14T03:56:00+0000"},"pdbx_vrpt_summary_em":[{"atom_inclusion_all_atoms":0.794,"atom_inclusion_backbone":0.909,"author_provided_fsc_resolution_by_cutoff_halfbit":3.51,"author_provided_fsc_resolution_by_cutoff_onebit":3.69,"author_provided_fsc_resolution_by_cutoff_pt143":3.46,"author_provided_fsc_resolution_by_cutoff_pt333":3.69,"author_provided_fsc_resolution_by_cutoff_pt5":3.87,"author_provided_fsc_resolution_by_cutoff_threesigma":3.09,"calculated_fsc_resolution_by_cutoff_halfbit":7.07,"calculated_fsc_resolution_by_cutoff_onebit":8.16,"calculated_fsc_resolution_by_cutoff_pt143":6.44,"calculated_fsc_resolution_by_cutoff_pt333":8.12,"calculated_fsc_resolution_by_cutoff_pt5":8.97,"calculated_fsc_resolution_by_cutoff_threesigma":3.75,"contour_level_primary_map":0.19,"exp_method":"electron microscopy","qscore":0.433}],"pdbx_vrpt_summary_geometry":[{"angles_rmsz":0.55,"bonds_rmsz":0.31,"clashscore":13.53,"num_hreduce":21713,"num_angles_rmsz":30630,"num_bonds_rmsz":22468,"percent_ramachandran_outliers":0.18,"percent_rotamer_outliers":0.47}],"rcsb_accession_info":{"deposit_date":"2020-02-10T00:00:00+0000","has_released_experimental_data":"Y","initial_release_date":"2020-02-26T00:00:00+0000","major_revision":2,"minor_revision":2,"revision_date":"2024-10-23T00:00:00+0000","status_code":"REL"},"rcsb_entry_container_identifiers":{"assembly_ids":["1"],"branched_entity_ids":["2"],"emdb_ids":["EMD-21375"],"entity_ids":["1","2","3"],"entry_id":"6VSB","model_ids":[1],"non_polymer_entity_ids":["3"],"polymer_entity_ids":["1"],"pubmed_id":32075877,"rcsb_id":"6VSB","related_emdb_ids":["EMD-21374"]},"rcsb_entry_info":{"assembly_count":1,"branched_entity_count":1,"branched_molecular_weight_maximum":0.42,"branched_molecular_weight_minimum":0.42,"cis_peptide_count":0,"deposited_atom_count":22854,"deposited_deuterated_water_count":0,"deposited_hydrogen_atom_count":0,"deposited_model_count":1,"deposited_modeled_polymer_monomer_count":2905,"deposited_nonpolymer_entity_instance_count":27,"deposited_polymer_entity_instance_count":3,"deposited_polymer_monomer_count":3864,"deposited_solvent_atom_count":0,"deposited_unmodeled_polymer_monomer_count":959,"disulfide_bond_count":35,"entity_count":3,"experimental_method":"EM","experimental_method_count":1,"inter_mol_covalent_bond_count":61,"inter_mol_metalic_bond_count":0,"molecular_weight":440.39,"na_polymer_entity_types":"Other","nonpolymer_bound_components":["NAG"],"nonpolymer_entity_count":1,"nonpolymer_molecular_weight_maximum":0.22,"nonpolymer_molecular_weight_minimum":0.22,"polymer_composition":"protein/oligosaccharide","polymer_entity_count":1,"polymer_entity_count_dna":0,"polymer_entity_count_rna":0,"polymer_entity_count_nucleic_acid":0,"polymer_entity_count_nucleic_acid_hybrid":0,"polymer_entity_count_protein":1,"polymer_entity_taxonomy_count":1,"polymer_molecular_weight_maximum":142.4,"polymer_molecular_weight_minimum":142.4,"polymer_monomer_count_maximum":1288,"polymer_monomer_count_minimum":1288,"resolution_combined":[3.46],"selected_polymer_entity_types":"Protein/Oligosaccharide","software_programs_combined":["CRYOSPARC","LEGINON","WARP"],"solvent_entity_coun

In [2]:
get_type("metal")

'CHEBI'

In [45]:
import gilda

scored_matches = gilda.ground("dimyristoylphosphatidylcholine", namespaces=["CHEBI"])
scored_matches

[ScoredMatch(Term(dimyristoylphosphatidylcholine,dimyristoylphosphatidylcholine,CHEBI,CHEBI:241349,dimyristoyl phosphatidylcholine,synonym,chebi,None,None,None),0.5555555555555556,Match(query=dimyristoylphosphatidylcholine,ref=dimyristoylphosphatidylcholine,exact=True,space_mismatch=False,dash_mismatches={},cap_combos=[])),
 ScoredMatch(Term(dimyristoylphosphatidylcholine,dimyristoylphosphatidylcholine,CHEBI,CHEBI:45240,1,2-di-O-myristoyl-sn-glycero-3-phosphocholine,synonym,chebi,None,None,None),0.5555555555555556,Match(query=dimyristoylphosphatidylcholine,ref=dimyristoylphosphatidylcholine,exact=True,space_mismatch=False,dash_mismatches={},cap_combos=[]))]

In [49]:
df = pd.read_csv("../results/ground_mol_gilda.tsv", sep="\t")
df["source"] = "gilda"

df.shape

(850, 9)

In [50]:
df2 = pd.read_csv("../results/ground_mol_chebi.tsv", sep="\t")
df2["source"] = "chebi"

df2.shape

(850, 9)

In [45]:
df.head(1)

,Entity_name,Type,Database,ID,Score,Name,URL,nb_res,source
0,popc,PubChem,PubChem,5497103,Not Available,[(2R)-3-hexadecanoyloxy-2-[(Z)-octadec-9-enoyl...,Not Available,Not Available,gilda

In [46]:
df2.head(1)

,Entity_name,Type,Database,ID,Score,Name,Stars,nb_res,source
0,popc,CHEBI/GILDA,CHEBI,73001,38.634342,1-hexadecanoyl-2-(9Z-octadecenoyl)-sn-glycero-...,3,1,chebi

In [55]:
# If column id is the same add both row of the df
df_merged = df.merge(df2, how="outer")

In [56]:
df_merged.head(10)

,Entity_name,Type,Database,ID,Score,Name,URL,nb_res,source,Stars
0,(s)-norcoclaurine,CHEBI/GILDA,CHEBI,17729,0.7338693052978766,(S)-norcoclaurine,https://bioregistry.io/chebi:17729,2,gilda,NaN
1,(s)-norcoclaurine,CHEBI/GILDA,CHEBI,17729,59.687695,(S)-norcoclaurine,NaN,3,chebi,3
2,"1,2-diauroyl-sn-glycero-3-phospocholine",PubChem,PubChem,NOT_FOUND,Not Available,NOT_AVAILABLE,NaN,Not Available,chebi,Not Available
3,"1,2-diauroyl-sn-glycero-3-phospocholine",PubChem,PubChem,NOT_FOUND,Not Available,NOT_AVAILABLE,Not Available,Not Available,gilda,NaN
4,"1,2-dimyristoyl-sn-glycero-3-phosphocholine",CHEBI/GILDA,CHEBI,45240,0.5555555555555556,"1,2-dimyristoyl-sn-glycero-3-phosphocholine",https://bioregistry.io/chebi:45240,1,gilda,NaN
5,"1,2-dimyristoyl-sn-glycero-3-phosphocholine",CHEBI/GILDA,CHEBI,45240,74.1687,"1,2-di-O-myristoyl-sn-glycero-3-phosphocholine",NaN,1,chebi,3
6,"1,2-dioleoyl-sn-glycero-3-phosphocholine",CHEBI/GILDA,CHEBI,52360,73.81452,"1,2-dioleoyl-sn-glycero-3-phosphocholine(1+)",NaN,2,chebi,3
7,"1,2-dioleoyl-sn-glycero-3-phosphocholine",CHEBI/GILDA,CHEBI,74669,0.7777777777777778,"1,2-dioleoyl-sn-glycero-3-phosphocholine",https://bioregistry.io/chebi:74669,2,gilda,NaN
8,"1,2-dipalmitoyl-sn-glycero-3-phospcholine",PubChem,PubChem,NOT_FOUND,Not Available,NOT_AVAILABLE,NaN,Not Available,chebi,Not Available
9,"1,2-dipalmitoyl-sn-glycero-3-phospcholine",PubChem,PubChem,NOT_FOUND,Not Available,NOT_AVAILABLE,Not Available,Not Available,gilda,NaN

In [57]:
df_merged = df_merged.drop("Type", axis=1)

In [58]:
df_merged = df_merged.drop("URL", axis=1)
df_merged

,Entity_name,Database,ID,Score,Name,nb_res,source,Stars
0,(s)-norcoclaurine,CHEBI,17729,0.7338693052978766,(S)-norcoclaurine,2,gilda,NaN
1,(s)-norcoclaurine,CHEBI,17729,59.687695,(S)-norcoclaurine,3,chebi,3
2,"1,2-diauroyl-sn-glycero-3-phospocholine",PubChem,NOT_FOUND,Not Available,NOT_AVAILABLE,Not Available,chebi,Not Available
3,"1,2-diauroyl-sn-glycero-3-phospocholine",PubChem,NOT_FOUND,Not Available,NOT_AVAILABLE,Not Available,gilda,NaN
4,"1,2-dimyristoyl-sn-glycero-3-phosphocholine",CHEBI,45240,0.5555555555555556,"1,2-dimyristoyl-sn-glycero-3-phosphocholine",1,gilda,NaN
...,...,...,...,...,...,...,...,...
1695,β-lactamases,PubChem,NOT_FOUND,Not Available,NOT_AVAILABLE,Not Available,gilda,NaN
1696,βcd,CHEBI,22977,11.919747,cadmium atom,3,chebi,3
1697,βcd,CHEBI,495055,0.5400948258091115,beta-CD,1,gilda,NaN
1698,β‑cyclodextrin,CHEBI,495055,0.7619047619047619,beta-cyclodextrin,1,gilda,NaN
1699,β‑cyclodextrin,CHEBI,495055,38.977585,beta-cyclodextrin,5,chebi,3

In [59]:
df_merged = df_merged.drop("Stars", axis=1)
df_merged

,Entity_name,Database,ID,Score,Name,nb_res,source
0,(s)-norcoclaurine,CHEBI,17729,0.7338693052978766,(S)-norcoclaurine,2,gilda
1,(s)-norcoclaurine,CHEBI,17729,59.687695,(S)-norcoclaurine,3,chebi
2,"1,2-diauroyl-sn-glycero-3-phospocholine",PubChem,NOT_FOUND,Not Available,NOT_AVAILABLE,Not Available,chebi
3,"1,2-diauroyl-sn-glycero-3-phospocholine",PubChem,NOT_FOUND,Not Available,NOT_AVAILABLE,Not Available,gilda
4,"1,2-dimyristoyl-sn-glycero-3-phosphocholine",CHEBI,45240,0.5555555555555556,"1,2-dimyristoyl-sn-glycero-3-phosphocholine",1,gilda
...,...,...,...,...,...,...,...
1695,β-lactamases,PubChem,NOT_FOUND,Not Available,NOT_AVAILABLE,Not Available,gilda
1696,βcd,CHEBI,22977,11.919747,cadmium atom,3,chebi
1697,βcd,CHEBI,495055,0.5400948258091115,beta-CD,1,gilda
1698,β‑cyclodextrin,CHEBI,495055,0.7619047619047619,beta-cyclodextrin,1,gilda
1699,β‑cyclodextrin,CHEBI,495055,38.977585,beta-cyclodextrin,5,chebi

In [60]:
df_merged = df_merged.iloc[:, [0, 6, 1, 2, 4, 3, 5]]

In [61]:
df_merged

,Entity_name,source,Database,ID,Name,Score,nb_res
0,(s)-norcoclaurine,gilda,CHEBI,17729,(S)-norcoclaurine,0.7338693052978766,2
1,(s)-norcoclaurine,chebi,CHEBI,17729,(S)-norcoclaurine,59.687695,3
2,"1,2-diauroyl-sn-glycero-3-phospocholine",chebi,PubChem,NOT_FOUND,NOT_AVAILABLE,Not Available,Not Available
3,"1,2-diauroyl-sn-glycero-3-phospocholine",gilda,PubChem,NOT_FOUND,NOT_AVAILABLE,Not Available,Not Available
4,"1,2-dimyristoyl-sn-glycero-3-phosphocholine",gilda,CHEBI,45240,"1,2-dimyristoyl-sn-glycero-3-phosphocholine",0.5555555555555556,1
...,...,...,...,...,...,...,...
1695,β-lactamases,gilda,PubChem,NOT_FOUND,NOT_AVAILABLE,Not Available,Not Available
1696,βcd,chebi,CHEBI,22977,cadmium atom,11.919747,3
1697,βcd,gilda,CHEBI,495055,beta-CD,0.5400948258091115,1
1698,β‑cyclodextrin,gilda,CHEBI,495055,beta-cyclodextrin,0.7619047619047619,1
1699,β‑cyclodextrin,chebi,CHEBI,495055,beta-cyclodextrin,38.977585,5

In [39]:
inter = pd.concat([df, df2], axis=1, join="inner")

In [40]:
inter.head()

,Entity_name,Type,Database,ID,Score,Name,URL,nb_res,Entity_name,Type,Database,ID,Name,Score,Stars,nb_res
0,popc,CHEBI/GILDA,NOT_FOUND,NOT_FOUND,NaN,NOT_FOUND,NOT_FOUND,NOT_FOUND,popc,CHEBI/GILDA,CHEBI,73001,1-hexadecanoyl-2-(9Z-octadecenoyl)-sn-glycero-...,38.634285,3,1
1,cholesterol,CHEBI/GILDA,CHEBI,CHEBI:16113,1.000000,cholesterol,https://bioregistry.io/chebi:16113,1,cholesterol,CHEBI/GILDA,CHEBI,16113,cholesterol,52.917076,3,170
2,dppc,CHEBI/GILDA,CHEBI,CHEBI:40265,0.540095,DPPC,https://bioregistry.io/chebi:40265,1,dppc,CHEBI/GILDA,CHEBI,40265,"1,2-di-O-palmitoyl-sn-glycero-3-phosphocholine",40.726196,3,1
3,nacl,CHEBI/GILDA,CHEBI,CHEBI:26710,0.521542,NaCl,https://bioregistry.io/chebi:26710,1,nacl,CHEBI/GILDA,CHEBI,26710,sodium chloride,40.726196,3,1
4,dmtap,CHEBI/GILDA,NOT_FOUND,NOT_FOUND,NaN,NOT_FOUND,NOT_FOUND,NOT_FOUND,dmtap,CHEBI/GILDA,CHEBI,Not Found,NaN,NaN,Not Found,Not Found

In [2]:
results = gilda.ground("1,2-Dioleoyl-sn-glycero-3-phosphocholine", namespaces=["CHEBI"])

In [8]:
len(results)
results[1]

ScoredMatch(Term(1,2dioleoylsnglycero3phosphocholine,1,2-DIOLEOYL-SN-GLYCERO-3-PHOSPHOCHOLINE,CHEBI,CHEBI:52360,1,2-dioleoyl-sn-glycero-3-phosphocholine(1+),synonym,chebi,None,None,None),0.5487528344671202,Match(query=1,2-Dioleoyl-sn-glycero-3-phosphocholine,ref=1,2-DIOLEOYL-SN-GLYCERO-3-PHOSPHOCHOLINE,exact=True,space_mismatch=False,dash_mismatches=set(),cap_combos=[('initial_cap', 'all_caps'), ('all_lower', 'all_caps'), ('all_lower', 'all_caps'), ('all_lower', 'all_caps')]))

In [13]:
API_CHEBI = "https://www.ebi.ac.uk/chebi/backend/api/public/es_search/"
parameters = {"term": "1,2-Dioleoyl-sn-glycero-3-phosphocholine", "page": 1, "size": 5}
response = httpx.get(f"{API_CHEBI}", params=parameters, timeout=30)
type(response)

INFO: [2026-03-31 09:42:49] httpx - HTTP Request: GET https://www.ebi.ac.uk/chebi/backend/api/public/es_search/?term=1%2C2-Dioleoyl-sn-glycero-3-phosphocholine&page=1&size=5 "HTTP/1.1 200 OK"

httpx.Response

In [30]:
res = response.__dict__["_content"].decode()

In [34]:
json.loads(res)["total"]

2

In [61]:
st = "ACDEFGHIKLMNPQRSTVWY"
st.lower()

'acdefghiklmnpqrstvwy'

In [ ]:
str_test = "`5"
str_test = str_test.replace("`", "'")
str_test

"'5"

In [21]:
response = httpx.get(
    "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/dmtap/JSON", timeout=30
)
response.status_code

INFO: [2026-04-03 14:16:43] httpx - HTTP Request: GET https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/dmtap/JSON "HTTP/1.1 200 OK"

200

In [32]:
data = response.json()
# ["InformationList"]["Information"][0]
# Get the score of the grounding pubchem
data

{'PC_Compounds': [{'id': {'id': {'cid': 10674918}},
   'atoms': {'aid': [1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     12,
     13,
     14,
     15,
     16,
     17,
     18,
     19,
     20,
     21,
     22,
     23,
     24,
     25,
     26,
     27,
     28,
     29,
     30,
     31,
     32,
     33,
     34,
     35,
     36,
     37,
     38,
     39,
     40,
     41,
     42,
     43,
     44,
     45,
     46,
     47,
     48,
     49,
     50,
     51,
     52,
     53,
     54,
     55,
     56,
     57,
     58,
     59,
     60,
     61,
     62,
     63,
     64,
     65,
     66,
     67,
     68,
     69,
     70,
     71,
     72,
     73,
     74,
     75,
     76,
     77,
     78,
     79,
     80,
     81,
     82,
     83,
     84,
     85,
     86,
     87,
     88,
     89,
     90,
     91,
     92,
     93,
     94,
     95,
     96,
     97,
     98,
     99,
     100,
     101,
     102,
     103,
     104,
     105,
     106,
     107,
     108],
    'element': [17,
     8,
     8,
     8,
     8,
     7,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1],
    'charge': [{'aid': 1, 'value': -1}, {'aid': 6, 'value': 1}]},
   'bonds': {'aid1': [2,
     2,
     3,
     3,
     4,
     5,
     6,
     6,
     6,
     6,
     7,
     7,
     7,
     8,
     8,
     9,
     9,
     9,
     10,
     10,
     10,
     11,
     11,
     11,
     12,
     12,
     13,
     13,
     13,
     13,
     14,
     14,
     14,
     15,
     15,
     15,
     16,
     16,
     16,
     17,
     17,
     17,
     18,
     18,
     18,
     18,
     19,
     19,
     19,
     20,
     20,
     20,
     21,
     21,
     21,
     22,
     22,
     22,
     23,
     23,
     23,
     24,
     24,
     24,
     25,
     25,
     25,
     26,
     26,
     26,
     27,
     27,
     27,
     28,
     28,
     28,
     29,
     29,
     29,
     31,
     31,
     31,
     32,
     32,
     32,
     33,
     33,
     33,
     34,
     34,
     34,
     35,
     35,
     35,
     37,
     37,
     37,
     38,
     38,
     38,
     39,
     39,
     39,
     40,
     40,
     40],
    'aid2': [8,
     30,
     12,
     36,
     30,
     36,
     7,
     9,
     10,
     11,
     8,
     41,
     42,
     12,
     43,
     44,
     45,
     46,
     47,
     48,
     49,
     50,
     51,
     52,
     53,
     54,
     14,
     15,
     55,
     56,
     16,
     57,
     58,
     17,
     59,
     60,
     21,
     61,
     62,
     23,
     63,
     64,
     19,
     20,
     65,
     66,
     22,
     67,
     68,
     24,
     69,
     70,
     27,
     71,
     72,
     25,
     73,
     74,
     26,
     75,
     76,
     28,
     77,
     78,
     29,
     79,
     80,
     30,
     81,
     82,
     31,
     83,
     84,
     32,
     85,
     86,
     33,
     87,
     88,
     34,
     89,
     90,
     35,
     91,
     92,
     36,
     93,
     94,
     37,
     95,
     96,
     38,
     97,
     98,
     39,
     99,
     100,
     40,
     101,
     102,
     103,
     104,
     105,
     106,
     107,
     108],
    'order': [1,
     1,
     1,
     1,
     2,
     2,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1]},
   'stereo': [{'tetrahedral': {'center': 8,
      'above': 2,
      'top': 7,
      'bottom': 12,
      'below': 43,
      'parity': 3,
      'type': 1}}],
   'coords': [{'type': [1, 5, 255],
     'aid': [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44,
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54,
      55,
      56,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66,
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76,
      77,
      78,
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88,
      89,
      90,
      91,
      92,
      93,
      94,
      95,
      96,
      97,
      98,
      99,
      100,
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108],
     'conformers': [{'x': [8.0812,
        12.6613,
        12.6613,
        11.7953,
        13.5273,
        15.2594,
        14.3933,
        13.5273,
        16.1254,
        15.7594,
        14.7594,
        13.5273,
        7.4651,
        6.5991,
        8.3312,
        5.7331,
        9.1972,
        10.0632,
        10.0632,
        9.1972,
        4.8671,
        10.9292,
        10.0632,
        9.1972,
        10.9292,
        10.9292,
        4.001,
        8.3312,
        11.7953,
        11.7953,
        3.135,
        8.3312,
        11.7953,
        2.269,
        7.4651,
        12.6613,
        1.403,
        7.4651,
        0.5369,
        6.5991,
        14.7919,
        13.9948,
        13.5273,
        15.8154,
        16.6623,
        16.4354,
        16.2963,
        16.0694,
        15.2224,
        14.2224,
        14.4494,
        15.2963,
        13.7394,
        14.1379,
        7.8637,
        7.0666,
        6.2006,
        6.9976,
        7.9326,
        8.7297,
        6.1316,
        5.3346,
        9.5957,
        8.7987,
        10.2753,
        10.6738,
        9.8512,
        9.4526,
        8.9851,
        8.5866,
        4.4685,
        5.2656,
        11.1413,
        11.5398,
        9.6647,
        10.4617,
        9.4092,
        9.8078,
        10.7172,
        10.3187,
        11.3278,
        10.5307,
        4.3996,
        3.6025,
        8.1191,
        7.7206,
        12.0073,
        12.4058,
        2.7365,
        3.5335,
        8.5432,
        8.9417,
        11.5832,
        11.1847,
        2.6675,
        1.8705,
        7.2531,
        6.8546,
        1.0044,
        1.8015,
        7.6772,
        8.0757,
        0.8469,
        0,
        0.2269,
        6.2891,
        6.0622,
        6.9091],
       'y': [0,
        15.5369,
        13.5369,
        14.0369,
        12.0369,
        15.0369,
        15.5369,
        15.0369,
        14.5369,
        15.903,
        14.1709,
        14.0369,
        15.5369,
        15.0369,
        15.0369,
        15.5369,
        15.5369,
        8.0369,
        9.0369,
        7.5369,
        15.0369,
        9.5369,
        15.0369,
        6.5369,
        10.5369,
        15.5369,
        15.5369,
        6.0369,
        11.0369,
        15.0369,
        15.0369,
        5.0369,
        12.0369,
        15.5369,
        4.5369,
        12.5369,
        15.0369,
        3.5369,
        15.5369,
        3.0369,
        16.0119,
        16.0119,
        15.6569,
        14,
        14.2269,
        15.0739,
        15.593,
        16.4399,
        16.213,
        14.4809,
        13.634,
        13.8609,
        13.4543,
        14.1446,
        16.0119,
        16.0119,
        14.562,
        14.562,
        14.562,
        14.562,
        16.0119,
        16.0119,
        16.0119,
        16.0119,
        7.4543,
        8.1446,
        9.6196,
        8.9293,
        8.1195,
        7.4293,
        14.562,
        14.562,
        8.9543,
        9.6446,
        14.562,
        14.562,
        5.9543,
        6.6446,
        11.1195,
        10.4293,
        16.0119,
        16.0119,
        16.0119,
        16.0119,
        6.6196,
        5.9293,
        10.4543,
        11.1446,
        14.562,
        14.562,
        4.4543,
        5.1446,
        12.6195,
        11.9293,
        16.0119,
        16.0119,
        5.1196,
        4.4293,
        14.562,
        14.562,
        2.9543,
        3.6446,
        16.0739,
        15.8469,
        15,
        3.5739,
        2.7269,
        2.5],
       'style': {'annotation': [3], 'aid1': [8], 'aid2': [7]}}]}],
   'charge': 0,
   'props': [{'urn': {'label': 'Compound',
      'name': 'Canonicalized',
      'datatype': 5,
      'release': '2019.01.04'},
     'value': {'ival': 1}},
    {'urn': {'label': 'Compound Complexity',
      'datatype': 7,
      'implementation': 'E_COMPLEXITY',
      'version': '3.4.8.24',
      'software': 'Cactvs',
      'source': 'Xemistry GmbH',
      'release': '2025.09.15'},
     'value': {'fval': 558}},
    {'urn': {'label': 'Count',
      'name': 'Hydrogen Bond Acceptor',
      'datatype': 5,
      'implementation': 'E_NHACCEPTORS',
      'version': '3.4.8.24',
      'software': 'Cactvs',
      'source': 'Xemistry GmbH',
      'release': '2025.09.15'},
     'value': {'ival': 5}},
    {'urn': {'label': 'Count',
      'name': 'Hydrogen Bond Donor',
      'datatype': 5,
      'implementation': 'E_NHDONORS',
      'version': '3.4.8.24',
      'software': 'Cactvs',
      'source': 'Xemistry GmbH',
      'release': '2025.09.15'},
     'value': {'ival': 0}},
    {'urn': {'label': 'Count',
      'name': 'Rotatable Bond',
      'datatype': 5,
      'implementation': 'E_NROTBONDS',
      'version': '3.4.8.24',
      'software': 'Cactvs',
      'source': 'Xemistry GmbH',
      'release': '2025.09.15'},
     'value': {'ival': 31}},
    {'urn': {'label': 'Fingerprint',
      'name': 'SubStructure Keys',
      'datatype': 16,
      'parameters': 'extended 2',
      'implementation': 'E_SCREEN',
      'version': '3.4.8.24',
      'software': 'Cactvs',
      'source': 'Xemistry GmbH',
      'release': '2025.09.15'},
     'value': {'binary': '00000371F07E3800040000000000000000000000000000000000000000000000000000000000001E00000000000814E1800602080300040008000090080000000000000000000108000003001200000007000006000012000188C8A08000000000000000000000000000000000000000000000'}},
    {'urn': {'label': 'IUPAC Name',
      'name': 'Allowed',
      'datatype': 1,
      'version': '2.9.3',
      'software': 'Lexichem TK',
      'source': 'OpenEye Scientific Software',
      'release': '2025.09.15'},
     'value': {'sval': '2,3-di(tetradecanoyloxy)propyl-trimethyl-ammonium chloride'}},
    {'urn': {'label': 'IUPAC Name',
      'name': 'CAS-like Style',
      'datatype': 1,
      'version': '2.9.3',
      'software': 'Lexichem TK',
      'source': 'OpenEye Scientific Software',
      'release': '2025.09.15'},
     'value': {'sval': '2,3-bis(1-oxotetradecoxy)propyl-trimethylammonium chloride'}},
    {'urn': {'label': 'IUPAC Name',
      'name': 'Markup',
      'datatype': 1,
      'version': '2.9.3',
      'software': 'Lexichem TK',
      'source': 'OpenEye Scientific Software',
      'release': '2025.09.15'},
     'value': {'sval': '2,3-di(tetradecanoyloxy)propyl-trimethylazanium chloride'}},
    {'urn': {'label': 'IUPAC Name',
      'name': 'Preferred',
      'datatype': 1,
      'version': '2.9.3',
      'software': 'Lexichem TK',
      'source': 'OpenEye Scientific Software',
      'release': '2025.09.15'},
     'value': {'sval': '2,3-di(tetradecanoyloxy)propyl-trimethylazanium chloride'}},
    {'urn': {'label': 'IUPAC Name',
      'name': 'Systematic',
      'datatype': 1,
      'version': '2.9.3',
      'software': 'Lexichem TK',
      'source': 'OpenEye Scientific Software',
      'release': '2025.09.15'},
     'value': {'sval': '2,3-di(tetradecanoyloxy)propyl-trimethyl-azanium chloride'}},
    {'urn': {'label': 'IUPAC Name',
      'name': 'Traditional',
      'datatype': 1,
      'version': '2.9.3',
      'software': 'Lexichem TK',
      'source': 'OpenEye Scientific Software',
      'release': '2025.09.15'},
     'value': {'sval': '2,3-di(tetradecanoyloxy)propyl-trimethyl-ammonium chloride'}},
    {'urn': {'label': 'InChI',
      'name': 'Standard',
      'datatype': 1,
      'version': '1.07.4',
      'software': 'InChI',
      'source': 'iupac.org',
      'release': '2025.09.15'},
     'value': {'sval': 'InChI=1S/C34H68NO4.ClH/c1-6-8-10-12-14-16-18-20-22-24-26-28-33(36)38-31-32(30-35(3,4)5)39-34(37)29-27-25-23-21-19-17-15-13-11-9-7-2;/h32H,6-31H2,1-5H3;1H/q+1;/p-1'}},
    {'urn': {'label': 'InChIKey',
      'name': 'Standard',
      'datatype': 1,
      'version': '1.07.4',
      'software': 'InChI',
      'source': 'iupac.org',
      'release': '2025.09.15'},
     'value': {'sval': 'WOSYUIOSAOFINL-UHFFFAOYSA-M'}},
    {'urn': {'label': 'Mass',
      'name': 'Exact',
      'datatype': 1,
      'version': '2.2',
      'software': 'PubChem',
      'source': 'ncbi.nlm.nih.gov',
      'release': '2025.09.15'},
     'value': {'sval': '589.4836873'}},
    {'urn': {'label': 'Molecular Formula',
      'datatype': 1,
      'version': '2.2',
      'software': 'PubChem',
      'source': 'ncbi.nlm.nih.gov',
      'release': '2025.09.15'},
     'value': {'sval': 'C34H68ClNO4'}},
    {'urn': {'label': 'Molecular Weight',
      'datatype': 1,
      'version': '2.2',
      'software': 'PubChem',
      'source': 'ncbi.nlm.nih.gov',
      'release': '2025.09.15'},
     'value': {'sval': '590.4'}},
    {'urn': {'label': 'SMILES',
      'name': 'Absolute',
      'datatype': 1,
      'version': '4.2.0',
      'software': 'OEChem',
      'source': 'OpenEye Scientific Software',
      'release': '2025.09.15'},
     'value': {'sval': 'CCCCCCCCCCCCCC(=O)OCC(C[N+](C)(C)C)OC(=O)CCCCCCCCCCCCC.[Cl-]'}},
    {'urn': {'label': 'SMILES',
      'name': 'Connectivity',
      'datatype': 1,
      'version': '4.2.0',
      'software': 'OEChem',
      'source': 'OpenEye Scientific Software',
      'release': '2025.09.15'},
     'value': {'sval': 'CCCCCCCCCCCCCC(=O)OCC(C[N+](C)(C)C)OC(=O)CCCCCCCCCCCCC.[Cl-]'}},
    {'urn': {'label': 'Topological',
      'name': 'Polar Surface Area',
      'datatype': 7,
      'implementation': 'E_TPSA',
      'version': '3.4.8.24',
      'software': 'Cactvs',
      'source': 'Xemistry GmbH',
      'release': '2025.09.15'},
     'value': {'fval': 52.6}},
    {'urn': {'label': 'Weight',
      'name': 'MonoIsotopic',
      'datatype': 1,
      'version': '2.2',
      'software': 'PubChem',
      'source': 'ncbi.nlm.nih.gov',
      'release': '2025.09.15'},
     'value': {'sval': '589.4836873'}}],
   'count': {'heavy_atom': 40,
    'atom_chiral': 1,
    'atom_chiral_def': 0,
    'atom_chiral_undef': 1,
    'bond_chiral': 0,
    'bond_chiral_def': 0,
    'bond_chiral_undef': 0,
    'isotope_atom': 0,
    'covalent_unit': 2,
    'tautomers': -1}}]}

In [ ]:
# Get the iupac name of the grounding pubchem
data["PropertyTable"]["Properties"][0]["IUPACName"]

KeyError: 'PropertyTable'

In [ ]:
compounds = data["PC_Compounds"]
num_results = len(compounds)

print(f"Number of results: {num_results}")

Number of results: 1

In [85]:
response.json().get("PC_Compounds")[0]

{'id': {'id': {'cid': 10674918}},
 'atoms': {'aid': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100,
   101,
   102,
   103,
   104,
   105,
   106,
   107,
   108],
  'element': [17,
   8,
   8,
   8,
   8,
   7,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   6,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1],
  'charge': [{'aid': 1, 'value': -1}, {'aid': 6, 'value': 1}]},
 'bonds': {'aid1': [2,
   2,
   3,
   3,
   4,
   5,
   6,
   6,
   6,
   6,
   7,
   7,
   7,
   8,
   8,
   9,
   9,
   9,
   10,
   10,
   10,
   11,
   11,
   11,
   12,
   12,
   13,
   13,
   13,
   13,
   14,
   14,
   14,
   15,
   15,
   15,
   16,
   16,
   16,
   17,
   17,
   17,
   18,
   18,
   18,
   18,
   19,
   19,
   19,
   20,
   20,
   20,
   21,
   21,
   21,
   22,
   22,
   22,
   23,
   23,
   23,
   24,
   24,
   24,
   25,
   25,
   25,
   26,
   26,
   26,
   27,
   27,
   27,
   28,
   28,
   28,
   29,
   29,
   29,
   31,
   31,
   31,
   32,
   32,
   32,
   33,
   33,
   33,
   34,
   34,
   34,
   35,
   35,
   35,
   37,
   37,
   37,
   38,
   38,
   38,
   39,
   39,
   39,
   40,
   40,
   40],
  'aid2': [8,
   30,
   12,
   36,
   30,
   36,
   7,
   9,
   10,
   11,
   8,
   41,
   42,
   12,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   14,
   15,
   55,
   56,
   16,
   57,
   58,
   17,
   59,
   60,
   21,
   61,
   62,
   23,
   63,
   64,
   19,
   20,
   65,
   66,
   22,
   67,
   68,
   24,
   69,
   70,
   27,
   71,
   72,
   25,
   73,
   74,
   26,
   75,
   76,
   28,
   77,
   78,
   29,
   79,
   80,
   30,
   81,
   82,
   31,
   83,
   84,
   32,
   85,
   86,
   33,
   87,
   88,
   34,
   89,
   90,
   35,
   91,
   92,
   36,
   93,
   94,
   37,
   95,
   96,
   38,
   97,
   98,
   39,
   99,
   100,
   40,
   101,
   102,
   103,
   104,
   105,
   106,
   107,
   108],
  'order': [1,
   1,
   1,
   1,
   2,
   2,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1]},
 'stereo': [{'tetrahedral': {'center': 8,
    'above': 2,
    'top': 7,
    'bottom': 12,
    'below': 43,
    'parity': 3,
    'type': 1}}],
 'coords': [{'type': [1, 5, 255],
   'aid': [1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    83,
    84,
    85,
    86,
    87,
    88,
    89,
    90,
    91,
    92,
    93,
    94,
    95,
    96,
    97,
    98,
    99,
    100,
    101,
    102,
    103,
    104,
    105,
    106,
    107,
    108],
   'conformers': [{'x': [8.0812,
      12.6613,
      12.6613,
      11.7953,
      13.5273,
      15.2594,
      14.3933,
      13.5273,
      16.1254,
      15.7594,
      14.7594,
      13.5273,
      7.4651,
      6.5991,
      8.3312,
      5.7331,
      9.1972,
      10.0632,
      10.0632,
      9.1972,
      4.8671,
      10.9292,
      10.0632,
      9.1972,
      10.9292,
      10.9292,
      4.001,
      8.3312,
      11.7953,
      11.7953,
      3.135,
      8.3312,
      11.7953,
      2.269,
      7.4651,
      12.6613,
      1.403,
      7.4651,
      0.5369,
      6.5991,
      14.7919,
      13.9948,
      13.5273,
      15.8154,
      16.6623,
      16.4354,
      16.2963,
      16.0694,
      15.2224,
      14.2224,
      14.4494,
      15.2963,
      13.7394,
      14.1379,
      7.8637,
      7.0666,
      6.2006,
      6.9976,
      7.9326,
      8.7297,
      6.1316,
      5.3346,
      9.5957,
      8.7987,
      10.2753,
      10.6738,
      9.8512,
      9.4526,
      8.9851,
      8.5866,
      4.4685,
      5.2656,
      11.1413,
      11.5398,
      9.6647,
      10.4617,
      9.4092,
      9.8078,
      10.7172,
      10.3187,
      11.3278,
      10.5307,
      4.3996,
      3.6025,
      8.1191,
      7.7206,
      12.0073,
      12.4058,
      2.7365,
      3.5335,
      8.5432,
      8.9417,
      11.5832,
      11.1847,
      2.6675,
      1.8705,
      7.2531,
      6.8546,
      1.0044,
      1.8015,
      7.6772,
      8.0757,
      0.8469,
      0,
      0.2269,
      6.2891,
      6.0622,
      6.9091],
     'y': [0,
      15.5369,
      13.5369,
      14.0369,
      12.0369,
      15.0369,
      15.5369,
      15.0369,
      14.5369,
      15.903,
      14.1709,
      14.0369,
      15.5369,
      15.0369,
      15.0369,
      15.5369,
      15.5369,
      8.0369,
      9.0369,
      7.5369,
      15.0369,
      9.5369,
      15.0369,
      6.5369,
      10.5369,
      15.5369,
      15.5369,
      6.0369,
      11.0369,
      15.0369,
      15.0369,
      5.0369,
      12.0369,
      15.5369,
      4.5369,
      12.5369,
      15.0369,
      3.5369,
      15.5369,
      3.0369,
      16.0119,
      16.0119,
      15.6569,
      14,
      14.2269,
      15.0739,
      15.593,
      16.4399,
      16.213,
      14.4809,
      13.634,
      13.8609,
      13.4543,
      14.1446,
      16.0119,
      16.0119,
      14.562,
      14.562,
      14.562,
      14.562,
      16.0119,
      16.0119,
      16.0119,
      16.0119,
      7.4543,
      8.1446,
      9.6196,
      8.9293,
      8.1195,
      7.4293,
      14.562,
      14.562,
      8.9543,
      9.6446,
      14.562,
      14.562,
      5.9543,
      6.6446,
      11.1195,
      10.4293,
      16.0119,
      16.0119,
      16.0119,
      16.0119,
      6.6196,
      5.9293,
      10.4543,
      11.1446,
      14.562,
      14.562,
      4.4543,
      5.1446,
      12.6195,
      11.9293,
      16.0119,
      16.0119,
      5.1196,
      4.4293,
      14.562,
      14.562,
      2.9543,
      3.6446,
      16.0739,
      15.8469,
      15,
      3.5739,
      2.7269,
      2.5],
     'style': {'annotation': [3], 'aid1': [8], 'aid2': [7]}}]}],
 'charge': 0,
 'props': [{'urn': {'label': 'Compound',
    'name': 'Canonicalized',
    'datatype': 5,
    'release': '2019.01.04'},
   'value': {'ival': 1}},
  {'urn': {'label': 'Compound Complexity',
    'datatype': 7,
    'implementation': 'E_COMPLEXITY',
    'version': '3.4.8.24',
    'software': 'Cactvs',
    'source': 'Xemistry GmbH',
    'release': '2025.09.15'},
   'value': {'fval': 558}},
  {'urn': {'label': 'Count',
    'name': 'Hydrogen Bond Acceptor',
    'datatype': 5,
    'implementation': 'E_NHACCEPTORS',
    'version': '3.4.8.24',
    'software': 'Cactvs',
    'source': 'Xemistry GmbH',
    'release': '2025.09.15'},
   'value': {'ival': 5}},
  {'urn': {'label': 'Count',
    'name': 'Hydrogen Bond Donor',
    'datatype': 5,
    'implementation': 'E_NHDONORS',
    'version': '3.4.8.24',
    'software': 'Cactvs',
    'source': 'Xemistry GmbH',
    'release': '2025.09.15'},
   'value': {'ival': 0}},
  {'urn': {'label': 'Count',
    'name': 'Rotatable Bond',
    'datatype': 5,
    'implementation': 'E_NROTBONDS',
    'version': '3.4.8.24',
    'software': 'Cactvs',
    'source': 'Xemistry GmbH',
    'release': '2025.09.15'},
   'value': {'ival': 31}},
  {'urn': {'label': 'Fingerprint',
    'name': 'SubStructure Keys',
    'datatype': 16,
    'parameters': 'extended 2',
    'implementation': 'E_SCREEN',
    'version': '3.4.8.24',
    'software': 'Cactvs',
    'source': 'Xemistry GmbH',
    'release': '2025.09.15'},
   'value': {'binary': '00000371F07E3800040000000000000000000000000000000000000000000000000000000000001E00000000000814E1800602080300040008000090080000000000000000000108000003001200000007000006000012000188C8A08000000000000000000000000000000000000000000000'}},
  {'urn': {'label': 'IUPAC Name',
    'name': 'Allowed',
    'datatype': 1,
    'version': '2.9.3',
    'software': 'Lexichem TK',
    'source': 'OpenEye Scientific Software',
    'release': '2025.09.15'},
   'value': {'sval': '2,3-di(tetradecanoyloxy)propyl-trimethyl-ammonium chloride'}},
  {'urn': {'label': 'IUPAC Name',
    'name': 'CAS-like Style',
    'datatype': 1,
    'version': '2.9.3',
    'software': 'Lexichem TK',
    'source': 'OpenEye Scientific Software',
    'release': '2025.09.15'},
   'value': {'sval': '2,3-bis(1-oxotetradecoxy)propyl-trimethylammonium chloride'}},
  {'urn': {'label': 'IUPAC Name',
    'name': 'Markup',
    'datatype': 1,
    'version': '2.9.3',
    'software': 'Lexichem TK',
    'source': 'OpenEye Scientific Software',
    'release': '2025.09.15'},
   'value': {'sval': '2,3-di(tetradecanoyloxy)propyl-trimethylazanium chloride'}},
  {'urn': {'label': 'IUPAC Name',
    'name': 'Preferred',
    'datatype': 1,
    'version': '2.9.3',
    'software': 'Lexichem TK',
    'source': 'OpenEye Scientific Software',
    'release': '2025.09.15'},
   'value': {'sval': '2,3-di(tetradecanoyloxy)propyl-trimethylazanium chloride'}},
  {'urn': {'label': 'IUPAC Name',
    'name': 'Systematic',
    'datatype': 1,
    'version': '2.9.3',
    'software': 'Lexichem TK',
    'source': 'OpenEye Scientific Software',
    'release': '2025.09.15'},
   'value': {'sval': '2,3-di(tetradecanoyloxy)propyl-trimethyl-azanium chloride'}},
  {'urn': {'label': 'IUPAC Name',
    'name': 'Traditional',
    'datatype': 1,
    'version': '2.9.3',
    'software': 'Lexichem TK',
    'source': 'OpenEye Scientific Software',
    'release': '2025.09.15'},
   'value': {'sval': '2,3-di(tetradecanoyloxy)propyl-trimethyl-ammonium chloride'}},
  {'urn': {'label': 'InChI',
    'name': 'Standard',
    'datatype': 1,
    'version': '1.07.4',
    'software': 'InChI',
    'source': 'iupac.org',
    'release': '2025.09.15'},
   'value': {'sval': 'InChI=1S/C34H68NO4.ClH/c1-6-8-10-12-14-16-18-20-22-24-26-28-33(36)38-31-32(30-35(3,4)5)39-34(37)29-27-25-23-21-19-17-15-13-11-9-7-2;/h32H,6-31H2,1-5H3;1H/q+1;/p-1'}},
  {'urn': {'label': 'InChIKey',
    'name': 'Standard',
    'datatype': 1,
    'version': '1.07.4',
    'software': 'InChI',
    'source': 'iupac.org',
    'release': '2025.09.15'},
   'value': {'sval': 'WOSYUIOSAOFINL-UHFFFAOYSA-M'}},
  {'urn': {'label': 'Mass',
    'name': 'Exact',
    'datatype': 1,
    'version': '2.2',
    'software': 'PubChem',
    'source': 'ncbi.nlm.nih.gov',
    'release': '2025.09.15'},
   'value': {'sval': '589.4836873'}},
  {'urn': {'label': 'Molecular Formula',
    'datatype': 1,
    'version': '2.2',
    'software': 'PubChem',
    'source': 'ncbi.nlm.nih.gov',
    'release': '2025.09.15'},
   'value': {'sval': 'C34H68ClNO4'}},
  {'urn': {'label': 'Molecular Weight',
    'datatype': 1,
    'version': '2.2',
    'software': 'PubChem',
    'source': 'ncbi.nlm.nih.gov',
    'release': '2025.09.15'},
   'value': {'sval': '590.4'}},
  {'urn': {'label': 'SMILES',
    'name': 'Absolute',
    'datatype': 1,
    'version': '4.2.0',
    'software': 'OEChem',
    'source': 'OpenEye Scientific Software',
    'release': '2025.09.15'},
   'value': {'sval': 'CCCCCCCCCCCCCC(=O)OCC(C[N+](C)(C)C)OC(=O)CCCCCCCCCCCCC.[Cl-]'}},
  {'urn': {'label': 'SMILES',
    'name': 'Connectivity',
    'datatype': 1,
    'version': '4.2.0',
    'software': 'OEChem',
    'source': 'OpenEye Scientific Software',
    'release': '2025.09.15'},
   'value': {'sval': 'CCCCCCCCCCCCCC(=O)OCC(C[N+](C)(C)C)OC(=O)CCCCCCCCCCCCC.[Cl-]'}},
  {'urn': {'label': 'Topological',
    'name': 'Polar Surface Area',
    'datatype': 7,
    'implementation': 'E_TPSA',
    'version': '3.4.8.24',
    'software': 'Cactvs',
    'source': 'Xemistry GmbH',
    'release': '2025.09.15'},
   'value': {'fval': 52.6}},
  {'urn': {'label': 'Weight',
    'name': 'MonoIsotopic',
    'datatype': 1,
    'version': '2.2',
    'software': 'PubChem',
    'source': 'ncbi.nlm.nih.gov',
    'release': '2025.09.15'},
   'value': {'sval': '589.4836873'}}],
 'count': {'heavy_atom': 40,
  'atom_chiral': 1,
  'atom_chiral_def': 0,
  'atom_chiral_undef': 1,
  'bond_chiral': 0,
  'bond_chiral_def': 0,
  'bond_chiral_undef': 0,
  'isotope_atom': 0,
  'covalent_unit': 2,
  'tautomers': -1}}

In [7]:
res_pubchem = call_pubchem("phosphoinositol phosphate")
res_pubchem

INFO: [2026-04-03 14:06:44] httpx - HTTP Request: GET https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/phosphoinositol%20phosphate/property/IUPACName,MolecularFormula/JSON "HTTP/1.1 200 OK"
2026-04-03 14:06:44.339 | DEBUG    | mdverse_entity_norm.scripts.ground_molecule:call_pubchem:279 - from PubChem: for phosphoinositol phosphate : -> Status HTTP : 200 (The request succeeded)
2026-04-03 14:06:44.341 | SUCCESS  | mdverse_entity_norm.scripts.ground_molecule:call_pubchem:284 - PubChem grounding successful for `phosphoinositol phosphate`.

{'entity_name': 'phosphoinositol phosphate',
 'database': 'PubChem',
 'id': 129651977,
 'name': 'Not Available',
 'molecular_formula': 'C6H8O12P2'}

In [ ]:
# Get the score of the grounding pubchem
pubchem_score = res_pubchem.get("score", "Not Available")
pubchem_score

'Not Available'

In [38]:
reschebi = call_chebi("α‑amylase")
reschebi

INFO: [2026-04-02 12:15:15] httpx - HTTP Request: GET https://www.ebi.ac.uk/chebi/backend/api/public/es_search/?term=%CE%B1%E2%80%91amylase&page=1&size=5 "HTTP/1.1 200 OK"
2026-04-02 12:15:15.863 | DEBUG    | mdverse_entity_norm.scripts.ground_molecule:call_chebi:203 - from ChEBI: for α‑amylase : -> Status HTTP : 200 (The request succeeded)

{'id': '50627',
 'score': 40.62963,
 'name': 'EC 3.2.1.1 (alpha-amylase) inhibitor',
 'star': 3,
 'nb_res': 5}

In [62]:
reschebi = call_chebi("dppc")
reschebi

INFO: [2026-04-02 14:55:56] httpx - HTTP Request: GET https://www.ebi.ac.uk/chebi/backend/api/public/es_search/?term=dppc&page=1&size=5 "HTTP/1.1 200 OK"
2026-04-02 14:55:56.979 | DEBUG    | mdverse_entity_norm.scripts.ground_molecule:call_chebi:206 - from ChEBI: for dppc : -> Status HTTP : 200 (The request succeeded)

{'id': '40265',
 'score': 40.726284,
 'name': '1,2-di-O-palmitoyl-sn-glycero-3-phosphocholine',
 'star': 3,
 'nb_res': 1}

In [5]:
resgilda = call_gilda("DPPC")
resgilda

2026-04-03 11:04:10.749 | INFO     | mdverse_entity_norm.scripts.ground_molecule:call_gilda:12 - Searching for `DPPC` using Gilda...
2026-04-03 11:04:10.750 | INFO     | mdverse_entity_norm.scripts.ground_molecule:call_gilda:15 - Using Gilda : for `DPPC` : The request succeeded
2026-04-03 11:04:10.750 | SUCCESS  | mdverse_entity_norm.scripts.ground_molecule:call_gilda:17 - Gilda grounding successful for `DPPC`.

{'database': 'CHEBI',
 'id': '40265',
 'score': 0.5555555555555556,
 'name': 'DPPC',
 'url': 'https://bioregistry.io/chebi:40265',
 'nb_res': 1}